import type { WallGraph } from '@/engine/parametric/wallGraph'

export interface AnchoredDimension {
  id: string
  type: 'overall' | 'bay' | 'opening'
  x1: number
  y1: number
  x2: number
  y2: number
  isHorizontal: boolean
  label: string
  valueM: number
}

export function autoGenerateDimensions(
  graph: WallGraph,
  planWidth: number,
  planHeight: number,
): AnchoredDimension[] {
  const dimensions: AnchoredDimension[] = []

  // Overall dimensions
  dimensions.push({
    id: 'dim-overall-w',
    type: 'overall',
    x1: 0,
    y1: 0,
    x2: planWidth,
    y2: 0,
    isHorizontal: true,
    label: `${Math.round(planWidth * 1000)}`,
    valueM: planWidth,
  })

  dimensions.push({
    id: 'dim-overall-h',
    type: 'overall',
    x1: 0,
    y1: 0,
    x2: 0,
    y2: planHeight,
    isHorizontal: false,
    label: `${Math.round(planHeight * 1000)}`,
    valueM: planHeight,
  })

  // Bay dimensions — find unique X positions from vertical edges
  const xPositions = new Set<number>()
  const yPositions = new Set<number>()

  for (const edge of graph.edges.values()) {
    const v1 = graph.vertices.get(edge.vertexIds[0])
    const v2 = graph.vertices.get(edge.vertexIds[1])
    if (!v1 || !v2) continue

    if (Math.abs(v1.y - v2.y) < 0.01) {
      xPositions.add(v1.x)
      xPositions.add(v2.x)
    }
    if (Math.abs(v1.x - v2.x) < 0.01) {
      yPositions.add(v1.y)
      yPositions.add(v2.y)
      xPositions.add(v1.x)
    }
  }

  xPositions.add(0)
  yPositions.add(0)

  const sortedX = [...xPositions].sort((a, b) => a - b)
  const sortedY = [...yPositions].sort((a, b) => b - a)

  for (let i = 0; i < sortedX.length - 1; i++) {
    const gap = sortedX[i + 1] - sortedX[i]
    if (gap > 0.3) {
      dimensions.push({
        id: `dim-bay-h-${i}`,
        type: 'bay',
        x1: sortedX[i],
        y1: 0,
        x2: sortedX[i + 1],
        y2: 0,
        isHorizontal: true,
        label: `${Math.round(gap * 1000)}`,
        valueM: gap,
      })
    }
  }

  for (let i = 0; i < sortedY.length - 1; i++) {
    const gap = sortedY[i] - sortedY[i + 1]
    if (gap > 0.3) {
      dimensions.push({
        id: `dim-bay-v-${i}`,
        type: 'bay',
        x1: 0,
        y1: sortedY[i + 1],
        x2: 0,
        y2: sortedY[i],
        isHorizontal: false,
        label: `${Math.round(gap * 1000)}`,
        valueM: gap,
      })
    }
  }

  return dimensions
}

export function resolveDimensionsToSvg(
  dimensions: AnchoredDimension[],
  scale: number,
  ox: number,
  oy: number,
): AnchoredDimension[] {
  return dimensions.map(d => ({
    ...d,
    x1: ox + d.x1 * scale,
    y1: oy - d.y1 * scale,
    x2: ox + d.x2 * scale,
    y2: oy - d.y2 * scale,
  }))
}

export function remapDimensions(
  _dimensions: AnchoredDimension[],
  graph: WallGraph,
  planWidth: number,
  planHeight: number,
): AnchoredDimension[] {
  return autoGenerateDimensions(graph, planWidth, planHeight)
}
