import { describe, it, expect } from 'vitest'
import type { PlanModel } from '@/domain/plan'
import { buildWallGraph, getSharedWalls, getExternalWalls, getRoomEdges } from '@/engine/parametric/wallGraph'
import { moveWall, resizeRoom, moveVertex, validateEdgeMove, moveWallInPlan } from '@/engine/parametric/parametricOps'
import { autoGenerateDimensions, resolveDimensionsToSvg, remapDimensions } from '@/engine/parametric/dimensionAnchor'

function makePlan(overrides?: Partial<PlanModel>): PlanModel {
  return {
    id: 'param-test-plan',
    designOptionId: 'test',
    width: 10,
    height: 8,
    wallThickness: 0.23,
    rooms: [
      { id: 'r1', name: 'Living', x: 0, y: 0, width: 6, height: 8 },
      { id: 'r2', name: 'Kitchen', x: 6, y: 0, width: 4, height: 8 },
    ],
    walls: [
      { id: 'w-bottom', start: { x: 0, y: 8 }, end: { x: 10, y: 8 }, thickness: 0.23, type: 'external' },
      { id: 'w-top', start: { x: 0, y: 0 }, end: { x: 10, y: 0 }, thickness: 0.23, type: 'external' },
      { id: 'w-left', start: { x: 0, y: 0 }, end: { x: 0, y: 8 }, thickness: 0.23, type: 'external' },
      { id: 'w-right', start: { x: 10, y: 0 }, end: { x: 10, y: 8 }, thickness: 0.23, type: 'external' },
      { id: 'w-partition', start: { x: 6, y: 0 }, end: { x: 6, y: 8 }, thickness: 0.115, type: 'internal' },
    ],
    openings: [
      { id: 'o1', wallId: 'w-bottom', kind: 'door', offset: 0.5, width: 0.9 },
    ],
    scaleLabel: '1:100',
    ...overrides,
  }
}

describe('buildWallGraph', () => {
  it('builds vertices and edges for simple plan', () => {
    const graph = buildWallGraph(makePlan())
    expect(graph.vertices.size).toBeGreaterThanOrEqual(4)
    expect(graph.edges.size).toBe(5)
  })

  it('detects shared walls between rooms', () => {
    const graph = buildWallGraph(makePlan())
    const shared = getSharedWalls(graph, 'r1', 'r2')
    expect(shared.length).toBeGreaterThanOrEqual(1)
    const wallIds = shared.map(s => s.wallId)
    expect(wallIds).toContain('w-partition')
  })

  it('detects external walls', () => {
    const graph = buildWallGraph(makePlan())
    const external = getExternalWalls(graph)
    expect(external.length).toBe(4)
  })

  it('returns room edges for each room', () => {
    const graph = buildWallGraph(makePlan())
    const r1Edges = getRoomEdges(graph, 'r1')
    const r2Edges = getRoomEdges(graph, 'r2')
    expect(r1Edges.length).toBeGreaterThanOrEqual(3)
    expect(r2Edges.length).toBeGreaterThanOrEqual(3)
  })

  it('creates faces for rooms', () => {
    const graph = buildWallGraph(makePlan())
    expect(graph.faces.size).toBe(2)
    const f1 = graph.faces.get('r1')
    expect(f1).toBeDefined()
    expect(f1!.edgeIds.length).toBeGreaterThanOrEqual(3)
  })

  it('snaps close vertices together', () => {
    const plan = makePlan()
    const graph = buildWallGraph(plan)
    // All walls should share corners within snap tolerance
    const edgeCount = graph.edges.size
    expect(edgeCount).toBe(plan.walls.length)
  })

  it('builds adjacency map', () => {
    const graph = buildWallGraph(makePlan())
    const firstVertex = [...graph.vertices.values()][0]
    expect(graph.adjacency.has(firstVertex.id)).toBe(true)
    expect(graph.adjacency.get(firstVertex.id)!.length).toBeGreaterThan(0)
  })
})

describe('moveWall', () => {
  it('moves a wall and resizes adjacent rooms', () => {
    const plan = makePlan()
    const result = moveWall(plan, 'e-w-partition', -0.5, 0)
    expect(result).not.toBeNull()
    expect(result!.type).toBe('wall-moved')
    const movedWall = result!.plan.walls.find(w => w.id === 'w-partition')
    expect(movedWall).toBeDefined()
    expect(movedWall!.start.x).toBeCloseTo(5.5, 5)
  })

  it('returns null for non-existent edge', () => {
    const result = moveWall(makePlan(), 'e-nonexistent', 0.5, 0)
    expect(result).toBeNull()
  })

  it('rejects move that would collapse a room', () => {
    const plan = makePlan()
    const result = moveWall(plan, 'e-w-partition', -5, 0)
    expect(result).toBeNull()
  })

  it('moves external wall', () => {
    const plan = makePlan()
    const result = moveWall(plan, 'e-w-right', 0, 0)
    expect(result).not.toBeNull()
    const movedWall = result!.plan.walls.find(w => w.id === 'w-right')
    expect(movedWall).toBeDefined()
  })

  it('produces valid plan after move', () => {
    const plan = makePlan()
    const result = moveWall(plan, 'e-w-bottom', 0, 0.5)
    expect(result).not.toBeNull()
    const movedWall = result!.plan.walls.find(w => w.id === 'w-bottom')
    expect(movedWall!.start.y).toBeCloseTo(8.5, 5)
  })
})

describe('validateEdgeMove', () => {
  it('validates valid move', () => {
    const plan = makePlan()
    const graph = buildWallGraph(plan)
    const result = validateEdgeMove(graph, 'e-w-partition', -0.3, 0, plan)
    expect(result.valid).toBe(true)
  })

  it('rejects move that shrinks room below min', () => {
    const plan = makePlan()
    const graph = buildWallGraph(plan)
    const result = validateEdgeMove(graph, 'e-w-partition', -5, 0, plan)
    expect(result.valid).toBe(false)
  })

  it('returns invalid for non-existent edge', () => {
    const plan = makePlan()
    const graph = buildWallGraph(plan)
    const result = validateEdgeMove(graph, 'e-fake', 0.1, 0, plan)
    expect(result.valid).toBe(false)
  })
})

describe('moveWallInPlan', () => {
  it('returns updated plan or null', () => {
    const plan = makePlan()
    const updated = moveWallInPlan(plan, 'w-partition', 0.5, 0)
    expect(updated).not.toBeNull()
    expect(updated!.walls.find(w => w.id === 'w-partition')!.start.x).toBeCloseTo(6.5, 5)
  })

  it('returns null for invalid move', () => {
    const plan = makePlan()
    const updated = moveWallInPlan(plan, 'w-partition', -6, 0)
    expect(updated).toBeNull()
  })
})

describe('resizeRoom', () => {
  it('resizes room and shifts adjacent rooms', () => {
    const plan = makePlan()
    const result = resizeRoom(plan, 'r1', 7, 8)
    expect(result).not.toBeNull()
    expect(result!.type).toBe('room-resized')
    const r1 = result!.plan.rooms.find(r => r.id === 'r1')
    expect(r1!.width).toBeCloseTo(7, 5)
    const r2 = result!.plan.rooms.find(r => r.id === 'r2')
    expect(r2!.x).toBeCloseTo(7, 5)
  })

  it('rejects resize below minimum', () => {
    const plan = makePlan()
    const result = resizeRoom(plan, 'r1', 0.2, 0.2)
    expect(result).toBeNull()
  })

  it('returns null for non-existent room', () => {
    const plan = makePlan()
    const result = resizeRoom(plan, 'nonexistent', 5, 5)
    expect(result).toBeNull()
  })

  it('resizes room smaller and shifts in opposite direction', () => {
    const plan = makePlan()
    const result = resizeRoom(plan, 'r1', 4, 8)
    expect(result).not.toBeNull()
    expect(result!.plan.rooms.find(r => r.id === 'r1')!.width).toBeCloseTo(4, 5)
  })
})

describe('moveVertex', () => {
  it('moves vertex and updates all connected walls', () => {
    const plan = makePlan()
    const result = moveVertex(plan, 10, 8, -1, 0)
    expect(result).not.toBeNull()
    expect(result!.type).toBe('vertex-moved')
  })

  it('returns null for non-existent vertex', () => {
    const plan = makePlan()
    const result = moveVertex(plan, 999, 999, 0.5, 0)
    expect(result).toBeNull()
  })
})

describe('autoGenerateDimensions', () => {
  it('generates overall dimensions', () => {
    const graph = buildWallGraph(makePlan())
    const dims = autoGenerateDimensions(graph, 10, 8)
    const overalls = dims.filter(d => d.type === 'overall')
    expect(overalls.length).toBe(2)
  })

  it('generates bay dimensions', () => {
    const graph = buildWallGraph(makePlan())
    const dims = autoGenerateDimensions(graph, 10, 8)
    const bays = dims.filter(d => d.type === 'bay')
    expect(bays.length).toBeGreaterThanOrEqual(1)
  })

  it('labels dimensions in mm', () => {
    const graph = buildWallGraph(makePlan())
    const dims = autoGenerateDimensions(graph, 10, 8)
    const overallW = dims.find(d => d.id === 'dim-overall-w')
    expect(overallW).toBeDefined()
    expect(overallW!.label).toBe('10000')
  })

  it('all dimensions have positive values', () => {
    const graph = buildWallGraph(makePlan())
    const dims = autoGenerateDimensions(graph, 10, 8)
    for (const d of dims) {
      expect(d.valueM).toBeGreaterThan(0)
    }
  })
})

describe('resolveDimensionsToSvg', () => {
  it('transforms dimension coordinates to SVG space', () => {
    const graph = buildWallGraph(makePlan())
    const dims = autoGenerateDimensions(graph, 10, 8)
    const svgDims = resolveDimensionsToSvg(dims, 40, 40, 300)
    for (const d of svgDims) {
      expect(d.x1).not.toBeNaN()
      expect(d.y1).not.toBeNaN()
      expect(d.x2).not.toBeNaN()
      expect(d.y2).not.toBeNaN()
    }
  })
})

describe('remapDimensions', () => {
  it('regenerates dimensions from graph', () => {
    const graph = buildWallGraph(makePlan())
    const oldDims = autoGenerateDimensions(graph, 10, 8)
    const newDims = remapDimensions(oldDims, graph, 10, 8)
    expect(newDims.length).toBe(oldDims.length)
  })
})
