import type { CadDocument } from '@/domain/ws6-types'
import type { TitleBlockMeta } from '@/lib/drawings/title-block'
import type { DrawingRegisterSheet } from '@/lib/drawings/drawing-register'

type InfoSheetSheet = Pick<DrawingRegisterSheet, 'sheetNumber' | 'title' | 'discipline' | 'disciplineLabel' | 'scale' | 'revision'> & {
  viewId?: string | null
}

function esc(s: string | number | undefined): string {
  return String(s ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
}

const VIEW_LABELS: Record<string, string> = {
  'plan': 'Architectural floor plan',
  'site-plan': 'Site context and boundary plan',
  'foundation': 'Foundation and substructure layout',
  'roof': 'Roof plan with slopes and drainage',
  'ceiling': 'Reflected ceiling plan',
  'electrical': 'Electrical services layout',
  'plumbing': 'Plumbing services layout',
  'hvac': 'HVAC services layout',
  'front': 'Front elevation',
  'rear': 'Rear elevation',
  'left': 'Left side elevation',
  'right': 'Right side elevation',
  'side': 'Side elevation',
  'section': 'Building section',
  'presentation': 'Composed presentation sheet',
  'schedule-door': 'Door schedule',
  'schedule-window': 'Window schedule',
  'schedule-structural': 'Structural element schedule',
  'register': 'Drawing register',
  'details': 'Construction details',
  'schedule-room': 'Room schedule',
  'standards': 'Drawing standards',
  'package': 'Drawing package summary',
}

interface MetaRow {
  label: string
  value: string | number | undefined
}

export function buildInfoSheetSvg(cad: CadDocument, meta: TitleBlockMeta, sheet: InfoSheetSheet): string {
  const rows: MetaRow[] = [
    { label: 'Drawing', value: sheet.title },
    { label: 'Sheet', value: sheet.sheetNumber },
    { label: 'Discipline', value: sheet.disciplineLabel ?? sheet.discipline },
    { label: 'Scale', value: sheet.scale },
    { label: 'Revision', value: sheet.revision },
    { label: 'Date', value: meta.date },
    { label: 'Project', value: meta.project },
    { label: 'Sheet type', value: VIEW_LABELS[sheet.viewId ?? ''] ?? 'Drawing sheet' },
  ]
  if (meta.provenanceSummary) rows.push({ label: 'Basis', value: meta.provenanceSummary })
  if (cad.floors.length > 0) rows.push({ label: 'Floors', value: cad.floors.map((f) => f.name).join(', ') })
  rows.push({ label: 'Walls', value: cad.walls.length })
  rows.push({ label: 'Openings', value: cad.openings.length })

  const rowSvg = rows.map((row, i) => {
    const y = 150 + i * 30
    return `
    <text x="70" y="${y}" style="font:11px 'Space Grotesk',Arial,sans-serif;font-weight:700;fill:#64748b;">${esc(row.label)}</text>
    <text x="210" y="${y}" style="font:11px Arial,sans-serif;fill:#e2e8f0;">${esc(row.value)}</text>`
  }).join('\n    ')

  return `<svg width="800" height="600" viewBox="0 0 800 600" xmlns="http://www.w3.org/2000/svg">
  <rect width="800" height="600" fill="#0b1220"/>
  <rect x="20" y="20" width="760" height="560" rx="6" fill="none" stroke="#334155" stroke-width="1.5"/>
  <rect x="30" y="30" width="740" height="540" rx="4" fill="#0f172a" stroke="#1e293b" stroke-width="1"/>
  <text x="60" y="84" style="font:16px 'Space Grotesk',Arial,sans-serif;font-weight:700;fill:#f8fafc;">${esc(sheet.title)}</text>
  <text x="60" y="106" style="font:12px Arial,sans-serif;fill:#94a3b8;">${esc(sheet.sheetNumber)} · ${esc(VIEW_LABELS[sheet.viewId ?? ''] ?? 'Drawing sheet')}</text>
  <line x1="60" y1="120" x2="740" y2="120" stroke="#1e293b" stroke-width="1"/>
  ${rowSvg}
  <text x="400" y="540" text-anchor="middle" style="font:11px Arial,sans-serif;fill:#475569;">
    Information sheet — expand to a dedicated drawing for construction issue. Generated by Budget Engineer Studio.
  </text>
</svg>`
}
