const VERSION = '4.0.0';

export type ArtifactType =
  | 'capability-manifest'
  | 'deployment-manifest'
  | 'evaluation-checklist'
  | 'supervised-guidance'
  | 'pilot-readiness'
  | 'evaluation-report';

export function buildArtifactFilename(artifactType: ArtifactType, format: 'html' | 'json' | 'txt', context?: string): string {
  const timestamp = new Date().toISOString().replace(/[:.]/g, '-').slice(0, 19);
  const base = `budget-engineer-v${VERSION}`;
  const ctx = context ? `-${context.replace(/[^a-z0-9-]/gi, '-').toLowerCase()}` : '';
  return `${base}-${artifactType}${ctx}-${timestamp}.${format}`;
}

export function triggerDownload(content: string, filename: string, mimeType: string): void {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export function downloadHtml(html: string, filename: string): void {
  const fullHtml = `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${filename}</title><style>
body{font-family:Arial,Helvetica,sans-serif;font-size:11px;line-height:1.5;color:#222;max-width:900px;margin:0 auto;padding:20px}
h1{font-size:16px;margin:0 0 4px;color:#111}
h2{font-size:13px;margin:16px 0 4px;color:#333}
h3{font-size:11px;margin:12px 0 2px;color:#444}
p{margin:4px 0;font-size:10px;color:#555}
table{width:100%;border-collapse:collapse;margin:8px 0;font-size:9px}
th,td{padding:4px 6px;border:1px solid #ddd;text-align:left}
th{background:#f5f5f5;font-weight:600}
.footer{margin-top:20px;padding-top:8px;border-top:1px solid #ddd;font-size:8px;color:#999}
.badge{display:inline-block;padding:1px 6px;border-radius:3px;font-size:8px;font-weight:600}
.badge-green{background:#e8f5e9;color:#2e7d32}
.badge-blue{background:#e3f2fd;color:#1565c0}
.badge-orange{background:#fff3e0;color:#e65100}
.badge-red{background:#fce4ec;color:#c62828}
.badge-amber{background:#fff8e1;color:#f59e0b}
</style></head><body>${html}<div class="footer">Generated by Budget Engineer v${VERSION} — ${new Date().toISOString()}</div></body></html>`;
  triggerDownload(fullHtml, filename, 'text/html;charset=utf-8');
}

export function downloadJson(data: unknown, filename: string): void {
  triggerDownload(JSON.stringify(data, null, 2), filename, 'application/json');
}

export function downloadText(text: string, filename: string): void {
  triggerDownload(text, filename, 'text/plain;charset=utf-8');
}
