import type {
  PilotObservation,
  PilotSession,
  PilotSeverity,
  PilotStatus,
} from './pilotFeedbackModel';
import { SEVERITY_LABELS, STATUS_LABELS, DOMAIN_LABELS, SEVERITY_ORDER } from './pilotFeedbackModel';
import { getUnresolvedBlockers, sortBySeverity } from './pilotIssueClassification';
import type { PilotReviewSummary } from './pilotReviewSummary';
import { generatePilotReviewSummary } from './pilotReviewSummary';
import { buildTrendData, formatTrendDataHtml, formatTrendDataText } from './pilotTrendAnalysis';
import { downloadHtml, downloadJson, downloadText } from '@/lib/commercial/artifactExporter';

const STYLE = `
body{font-family:Arial,Helvetica,sans-serif;font-size:11px;line-height:1.5;color:#222;max-width:900px;margin:0 auto;padding:20px}
h1{font-size:16px;margin:0 0 4px;color:#111}
h2{font-size:13px;margin:16px 0 4px;color:#333}
h3{font-size:11px;margin:12px 0 2px;color:#444}
p{margin:4px 0;font-size:10px;color:#555}
table{width:100%;border-collapse:collapse;margin:8px 0;font-size:9px}
th,td{padding:4px 6px;border:1px solid #ddd;text-align:left}
th{background:#f5f5f5;font-weight:600}
.footer{margin-top:20px;padding-top:8px;border-top:1px solid #ddd;font-size:8px;color:#999}
.badge{display:inline-block;padding:1px 6px;border-radius:3px;font-size:8px;font-weight:600}
.badge-red{background:#fce4ec;color:#c62828}
.badge-orange{background:#fff3e0;color:#e65100}
.badge-amber{background:#fff8e1;color:#f59e0b}
.badge-blue{background:#e3f2fd;color:#1565c0}
.badge-green{background:#e8f5e9;color:#2e7d32}
.badge-gray{background:#f5f5f5;color:#666}
`;

function wrapHtml(title: string, body: string): string {
  return `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title}</title><style>${STYLE}</style></head><body>${body}<div class="footer">Generated by Budget Engineer v4.0.0 — ${new Date().toISOString()}</div></body></html>`;
}

function severityBadge(severity: PilotSeverity): string {
  const map: Record<PilotSeverity, string> = {
    blocker: 'badge-red',
    major: 'badge-orange',
    minor: 'badge-amber',
    observation: 'badge-blue',
    enhancement: 'badge-green',
  };
  return `<span class="badge ${map[severity]}">${SEVERITY_LABELS[severity]}</span>`;
}

function statusBadge(status: PilotStatus): string {
  const map: Record<PilotStatus, string> = {
    'new': 'badge-red',
    'under-review': 'badge-orange',
    'action-planned': 'badge-amber',
    'resolved': 'badge-green',
    'accepted-limitation': 'badge-gray',
    'deferred': 'badge-gray',
  };
  return `<span class="badge ${map[status]}">${STATUS_LABELS[status]}</span>`;
}

export function formatPilotIssueLogHtml(
  session: PilotSession,
  observations: PilotObservation[]
): string {
  const sorted = sortBySeverity(observations);
  let table = `<h1>Pilot Issue Log</h1>
<p>Session: ${session.name} | Project: ${session.projectId} | ${observations.length} issues</p>
<table>
<thead><tr>
<th>Severity</th><th>Status</th><th>Domain</th><th>Title</th><th>Reviewer</th><th>Recommendation</th>
</tr></thead><tbody>`;

  for (const o of sorted) {
    table += `<tr>
<td>${severityBadge(o.severity)}</td>
<td>${statusBadge(o.status)}</td>
<td>${DOMAIN_LABELS[o.domain]}</td>
<td><strong>${o.title}</strong><br><span style="font-size:8px;color:#888">${o.description}</span></td>
<td>${o.reviewerName}</td>
<td style="font-size:8px">${o.recommendation || '—'}</td>
</tr>`;
  }

  table += `</tbody></table>`;
  return wrapHtml('Pilot Issue Log', table);
}

export function formatPilotSummaryReportHtml(summary: PilotReviewSummary): string {
  let html = `<h1>Pilot Review Summary</h1>
<p>${summary.sessionName} — Generated ${new Date(summary.generatedAt).toLocaleDateString()}</p>

<h2>Overview</h2>
<table>
<tr><td>Total Observations</td><td>${summary.totalObservations}</td></tr>
<tr><td>Resolution Rate</td><td>${summary.resolutionRate}%</td></tr>
<tr><td>Unresolved Blockers</td><td>${summary.unresolvedBlockers.length}</td></tr>
<tr><td>Recommendation</td><td><strong>${summary.recommendation}</strong></td></tr>
</table>

<h2>By Severity</h2>
<table><thead><tr><th>Severity</th><th>Count</th></tr></thead><tbody>`;

  for (const sev of SEVERITY_ORDER) {
    const count = summary.bySeverity[sev];
    html += `<tr><td>${severityBadge(sev)}</td><td>${count}</td></tr>`;
  }

  html += `</tbody></table>

<h2>By Domain</h2>
<table><thead><tr><th>Domain</th><th>Count</th><th>%</th></tr></thead><tbody>`;

  for (const d of summary.domainConcentration) {
    html += `<tr><td>${DOMAIN_LABELS[d.domain]}</td><td>${d.count}</td><td>${d.pct}%</td></tr>`;
  }

  html += `</tbody></table>

<h2>Resolution Status</h2>
<p>Open: ${summary.openVsResolved.open} | Resolved: ${summary.openVsResolved.resolved} | Total: ${summary.totalObservations}</p>

<h2>Recommendation</h2>
<p><strong>${summary.recommendation}</strong></p>
<p>${summary.recommendationReason}</p>`;

  return wrapHtml('Pilot Review Summary', html);
}

export function formatOpenBlockerReportHtml(observations: PilotObservation[]): string {
  const blockers = getUnresolvedBlockers(observations);
  let html = `<h1>Open Blockers Report</h1>
<p>${blockers.length} unresolved blocker(s)</p>`;

  if (blockers.length === 0) {
    html += `<p style="color:#22c55e">No unresolved blockers. Pilot can proceed.</p>`;
  } else {
    html += `<table><thead><tr><th>Domain</th><th>Title</th><th>Description</th><th>Reviewer</th></tr></thead><tbody>`;
    for (const b of blockers) {
      html += `<tr>
<td>${DOMAIN_LABELS[b.domain]}</td>
<td><strong>${b.title}</strong></td>
<td style="font-size:8px">${b.description}</td>
<td>${b.reviewerName}</td>
</tr>`;
    }
    html += `</tbody></table>`;
  }

  return wrapHtml('Open Blockers Report', html);
}

export function formatCloseoutRecommendationHtml(
  session: PilotSession,
  summary: PilotReviewSummary
): string {
  let html = `<h1>Pilot Closeout Recommendation</h1>
<p>Session: ${session.name} | ${new Date().toLocaleDateString()}</p>

<h2>Recommendation: ${summary.recommendation}</h2>
<p>${summary.recommendationReason}</p>

<h2>Session Details</h2>
<table>
<tr><td>Session ID</td><td>${session.id}</td></tr>
<tr><td>Project ID</td><td>${session.projectId}</td></tr>
<tr><td>Status</td><td>${session.status}</td></tr>
<tr><td>Lead Reviewer</td><td>${session.leadReviewer}</td></tr>
<tr><td>Start Date</td><td>${session.startDate}</td></tr>
${session.endDate ? `<tr><td>End Date</td><td>${session.endDate}</td></tr>` : ''}
</table>

<h2>Summary Metrics</h2>
<table>
<tr><td>Total Observations</td><td>${summary.totalObservations}</td></tr>
<tr><td>Open Items</td><td>${summary.openVsResolved.open}</td></tr>
<tr><td>Resolved Items</td><td>${summary.openVsResolved.resolved}</td></tr>
<tr><td>Resolution Rate</td><td>${summary.resolutionRate}%</td></tr>
<tr><td>Unresolved Blockers</td><td>${summary.unresolvedBlockers.length}</td></tr>
</table>`;

  if (summary.unresolvedBlockers.length > 0) {
    html += `<h2>Unresolved Blockers (Must Resolve Before Closeout)</h2><ul>`;
    for (const b of summary.unresolvedBlockers) {
      html += `<li style="font-size:9px;color:#c62828"><strong>${b.title}</strong> (${DOMAIN_LABELS[b.domain]}) — ${b.description}</li>`;
    }
    html += `</ul>`;
  }

  return wrapHtml('Pilot Closeout Recommendation', html);
}

export function formatPilotIssueLogJson(
  session: PilotSession,
  observations: PilotObservation[]
): string {
  return JSON.stringify({ session, observations, exportedAt: new Date().toISOString() }, null, 2);
}

export function formatPilotSummaryText(summary: PilotReviewSummary): string {
  const lines: string[] = [
    `Pilot Review Summary — ${summary.sessionName}`,
    `Generated: ${new Date(summary.generatedAt).toLocaleDateString()}`,
    '',
    `Total Observations: ${summary.totalObservations}`,
    `Resolution Rate: ${summary.resolutionRate}%`,
    `Recommendation: ${summary.recommendation}`,
    '',
    `By Severity:`,
    ...SEVERITY_ORDER.filter(s => summary.bySeverity[s] > 0).map(s => `  ${SEVERITY_LABELS[s]}: ${summary.bySeverity[s]}`),
    '',
    `Open: ${summary.openVsResolved.open} | Resolved: ${summary.openVsResolved.resolved}`,
    '',
    `Recommendation Reason: ${summary.recommendationReason}`,
  ];
  return lines.join('\n');
}

export function downloadPilotIssueLog(
  session: PilotSession,
  observations: PilotObservation[]
): void {
  downloadHtml(
    formatPilotIssueLogHtml(session, observations),
    `pilot-issue-log-${session.id.slice(0, 8)}.html`
  );
}

export function downloadPilotSummaryReport(
  session: PilotSession,
  observations: PilotObservation[]
): void {
  const summary = generatePilotReviewSummary(session, observations);
  downloadHtml(
    formatPilotSummaryReportHtml(summary),
    `pilot-summary-${session.id.slice(0, 8)}.html`
  );
  downloadJson(
    formatPilotIssueLogJson(session, observations),
    `pilot-issue-log-${session.id.slice(0, 8)}.json`
  );
}

export function downloadOpenBlockerReport(observations: PilotObservation[]): void {
  downloadHtml(
    formatOpenBlockerReportHtml(observations),
    `pilot-open-blockers-${Date.now()}.html`
  );
}

export function downloadCloseoutRecommendation(
  session: PilotSession,
  observations: PilotObservation[]
): void {
  const summary = generatePilotReviewSummary(session, observations);
  downloadHtml(
    formatCloseoutRecommendationHtml(session, summary),
    `pilot-closeout-recommendation-${session.id.slice(0, 8)}.html`
  );
  downloadText(
    formatPilotSummaryText(summary),
    `pilot-summary-${session.id.slice(0, 8)}.txt`
  );
}

export function formatMultiSessionSummaryHtml(
  sessions: PilotSession[],
  allObservations: PilotObservation[]
): string {
  const trend = buildTrendData(sessions, allObservations);
  let html = `<h1>Multi-Session Pilot Summary</h1>
<p>${sessions.length} sessions, ${allObservations.length} total observations</p>

<h2>Session Overview</h2>
<table><thead><tr>
<th>Session</th><th>Status</th><th>Observations</th><th>Blockers</th><th>Major</th><th>Resolved</th><th>Rate</th><th>Readiness Tier</th>
</tr></thead><tbody>`;

  const sorted = [...sessions].sort(
    (a, b) => new Date(a.startDate).getTime() - new Date(b.startDate).getTime()
  );
  for (const session of sorted) {
    const sessionObs = allObservations.filter(o => o.sessionId === session.id);
    const blockers = getUnresolvedBlockers(sessionObs);
    const resolved = sessionObs.filter(o => o.status === 'resolved' || o.status === 'accepted-limitation').length;
    const major = sessionObs.filter(o => o.severity === 'major').length;
    const rate = sessionObs.length > 0 ? Math.round((resolved / sessionObs.length) * 100) : 0;
    const tier = session.readinessContext?.tier ?? '—';
    html += `<tr>
<td><strong>${session.name}</strong></td>
<td>${session.status}</td>
<td>${sessionObs.length}</td>
<td>${blockers.length}</td>
<td>${major}</td>
<td>${resolved}</td>
<td>${rate}%</td>
<td>${tier}</td>
</tr>`;
  }

  html += `</tbody></table>

<h2>Overall Trend</h2>
<p>${trend.overallAssessment}</p>`;

  return html;
}

export function formatTrendReportHtml(
  sessions: PilotSession[],
  allObservations: PilotObservation[]
): string {
  const trend = buildTrendData(sessions, allObservations);
  return formatTrendDataHtml(trend);
}

export function formatTrendReportText(
  sessions: PilotSession[],
  allObservations: PilotObservation[]
): string {
  const trend = buildTrendData(sessions, allObservations);
  return formatTrendDataText(trend);
}

export function formatSessionComparisonHtml(
  sessions: PilotSession[],
  allObservations: PilotObservation[]
): string {
  const sorted = [...sessions].sort(
    (a, b) => new Date(a.startDate).getTime() - new Date(b.startDate).getTime()
  );
  if (sorted.length < 2) {
    const t = formatTrendDataText(buildTrendData(sessions, allObservations));
    return `<h1>Session Comparison</h1><p>At least 2 sessions needed for comparison.</p><p>Trend: ${t}</p>`;
  }

  const first = sorted[0];
  const last = sorted[sorted.length - 1];
  const firstObs = allObservations.filter(o => o.sessionId === first.id);
  const lastObs = allObservations.filter(o => o.sessionId === last.id);
  const firstBlockers = getUnresolvedBlockers(firstObs).length;
  const lastBlockers = getUnresolvedBlockers(lastObs).length;
  const firstResolved = firstObs.filter(o => o.status === 'resolved' || o.status === 'accepted-limitation').length;
  const lastResolved = lastObs.filter(o => o.status === 'resolved' || o.status === 'accepted-limitation').length;
  const firstRate = firstObs.length > 0 ? Math.round((firstResolved / firstObs.length) * 100) : 0;
  const lastRate = lastObs.length > 0 ? Math.round((lastResolved / lastObs.length) * 100) : 0;

  let html = `<h1>Session Comparison</h1>
<p>Comparing earliest ("${first.name}") vs latest ("${last.name}") session</p>

<table>
<thead><tr><th>Metric</th><th>${first.name}</th><th>${last.name}</th><th>Delta</th></tr></thead><tbody>
<tr><td>Observations</td><td>${firstObs.length}</td><td>${lastObs.length}</td><td>${lastObs.length - firstObs.length >= 0 ? '+' : ''}${lastObs.length - firstObs.length}</td></tr>
<tr><td>Unresolved Blockers</td><td>${firstBlockers}</td><td>${lastBlockers}</td><td>${lastBlockers - firstBlockers >= 0 ? '+' : ''}${lastBlockers - firstBlockers}</td></tr>
<tr><td>Resolution Rate</td><td>${firstRate}%</td><td>${lastRate}%</td><td>${lastRate - firstRate >= 0 ? '+' : ''}${lastRate - firstRate}%</td></tr>
`;

  const firstTier = first.readinessContext?.tier ?? null;
  const lastTier = last.readinessContext?.tier ?? null;
  if (firstTier || lastTier) {
    html += `<tr><td>Readiness Tier</td><td>${firstTier ?? '—'}</td><td>${lastTier ?? '—'}</td><td>—</td></tr>`;
  }
  const firstScore = first.readinessContext?.benchmarkScore ?? null;
  const lastScore = last.readinessContext?.benchmarkScore ?? null;
  if (firstScore !== null || lastScore !== null) {
    const delta = firstScore !== null && lastScore !== null ? lastScore - firstScore : 0;
    html += `<tr><td>Benchmark Score</td><td>${firstScore !== null ? firstScore + '%' : '—'}</td><td>${lastScore !== null ? lastScore + '%' : '—'}</td><td>${delta >= 0 ? '+' : ''}${delta}%</td></tr>`;
  }

  html += `</tbody></table>`;

  const trend = buildTrendData(sessions, allObservations);
  html += `<h2>Overall Trend</h2><p>${trend.overallAssessment}</p>`;

  return html;
}

export function formatMultiSessionSummaryText(
  sessions: PilotSession[],
  allObservations: PilotObservation[]
): string {
  const lines: string[] = [
    'Multi-Session Pilot Summary',
    `${sessions.length} sessions, ${allObservations.length} total observations`,
    '',
  ];

  const sorted = [...sessions].sort(
    (a, b) => new Date(a.startDate).getTime() - new Date(b.startDate).getTime()
  );
  for (const session of sorted) {
    const sessionObs = allObservations.filter(o => o.sessionId === session.id);
    const blockers = getUnresolvedBlockers(sessionObs).length;
    const resolved = sessionObs.filter(o => o.status === 'resolved' || o.status === 'accepted-limitation').length;
    const rate = sessionObs.length > 0 ? Math.round((resolved / sessionObs.length) * 100) : 0;
    const tier = session.readinessContext?.tier ?? '—';
    lines.push(`  ${session.name}: ${sessionObs.length} obs, ${blockers} blockers, ${rate}% resolved, tier: ${tier}`);
  }

  const trend = buildTrendData(sessions, allObservations);
  lines.push('', 'Overall Trend:', `  ${trend.overallAssessment}`);

  return lines.join('\n');
}

export function downloadMultiSessionSummary(
  sessions: PilotSession[],
  allObservations: PilotObservation[]
): void {
  const html = formatMultiSessionSummaryHtml(sessions, allObservations);
  const STYLE = `
body{font-family:Arial,Helvetica,sans-serif;font-size:11px;line-height:1.5;color:#222;max-width:900px;margin:0 auto;padding:20px}
h1{font-size:16px;margin:0 0 4px;color:#111}
h2{font-size:13px;margin:16px 0 4px;color:#333}
p{margin:4px 0;font-size:10px;color:#555}
table{width:100%;border-collapse:collapse;margin:8px 0;font-size:9px}
th,td{padding:4px 6px;border:1px solid #ddd;text-align:left}
th{background:#f5f5f5;font-weight:600}
.footer{margin-top:20px;padding-top:8px;border-top:1px solid #ddd;font-size:8px;color:#999}
`;
  const wrapped = `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Multi-Session Pilot Summary</title><style>${STYLE}</style></head><body>${html}<div class="footer">Generated by Budget Engineer v4.0.0 — ${new Date().toISOString()}</div></body></html>`;
  downloadHtml(wrapped, `pilot-multi-session-summary-${Date.now()}.html`);
  downloadText(formatMultiSessionSummaryText(sessions, allObservations), `pilot-multi-session-summary-${Date.now()}.txt`);
}

export function downloadTrendReport(
  sessions: PilotSession[],
  allObservations: PilotObservation[]
): void {
  const html = formatTrendReportHtml(sessions, allObservations);
  downloadHtml(html, `pilot-trend-report-${Date.now()}.html`);
  downloadText(formatTrendReportText(sessions, allObservations), `pilot-trend-report-${Date.now()}.txt`);
}

export function downloadSessionComparison(
  sessions: PilotSession[],
  allObservations: PilotObservation[]
): void {
  const html = formatSessionComparisonHtml(sessions, allObservations);
  const STYLE = `
body{font-family:Arial,Helvetica,sans-serif;font-size:11px;line-height:1.5;color:#222;max-width:900px;margin:0 auto;padding:20px}
h1{font-size:16px;margin:0 0 4px;color:#111}
h2{font-size:13px;margin:16px 0 4px;color:#333}
p{margin:4px 0;font-size:10px;color:#555}
table{width:100%;border-collapse:collapse;margin:8px 0;font-size:9px}
th,td{padding:4px 6px;border:1px solid #ddd;text-align:left}
th{background:#f5f5f5;font-weight:600}
.footer{margin-top:20px;padding-top:8px;border-top:1px solid #ddd;font-size:8px;color:#999}
`;
  const wrapped = `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Session Comparison</title><style>${STYLE}</style></head><body>${html}<div class="footer">Generated by Budget Engineer v4.0.0 — ${new Date().toISOString()}</div></body></html>`;
  downloadHtml(wrapped, `pilot-session-comparison-${Date.now()}.html`);
  downloadText(formatMultiSessionSummaryText(sessions, allObservations), `pilot-multi-session-summary-${Date.now()}.txt`);
}
