export { getPenAssignment, getLineWeight, dxfLineWeightCode, dxfLayerColor, PEN_TABLE } from './pen-table'
export type { PenAssignment, LineWeight } from './pen-table'
export { getLinetype, linetypeForLayer, dxfLinetypeName, LINETYPES } from './linetypes'
export type { LinetypeDef } from './linetypes'
export { getHatchPattern, hatchPatternForMaterial, svgHatchPattern, HATCH_PATTERNS } from './hatch-patterns'
export type { HatchPatternDef } from './hatch-patterns'
export { getTextStyle, textStyleForPurpose, svgFontDeclaration, TEXT_STYLES } from './text-styles'
export type { TextStyleDef, FontFamily } from './text-styles'
